on: [push, pull_request]
name: Test
jobs:
  setup-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install Deps
      run: sudo apt install -y libusb-1.0- libgtk-3-dev libappindicator3-dev

  setup-macos:
    runs-on: macos-latest
    steps:
    - name: Install Deps
      run: brew install libusb

  test:
    needs: [setup-linux,setup-macos]
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
