on: [push, pull_request]
name: Test
jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install Deps
      run: sudo apt install -y libusb-1.0-0-dev libgtk-3-dev libappindicator3-dev
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
        
  test-macos:
    runs-on: macos-latest
    steps:
    - name: Install Deps
      run: brew install libusb
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
